application:
  name: "dumb-data-viz-api"
data:
  pagination: 1000
  endpoints:
    crime: "https://data.cityofchicago.org/resource/crimes.json"
    311requests: "https://data.cityofchicago.org/resource/v6vf-nfxy.json"